
--  ZOMATO SQL ANALYSIS PROJECT
-- ==========================================================

-- 1️. Top 3 customers who have placed the highest number of orders
SELECT 
    c.customer_id,
    c.customer_name,
    COUNT(o.order_id) AS total_orders
FROM order_detail o
JOIN customer c ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY total_orders DESC
LIMIT 3;



-- 2️. Restaurant with the highest average rating

SELECT 
    restaurant_name,
    rlocation,
    rrating
FROM restaurant
ORDER BY rrating DESC
LIMIT 1;




-- 3️. Orders delivered in under 30 minutes
SELECT 
    order_id,
    customer_id,
    restaurant_id,
    employee_id,
    TIMESTAMPDIFF(MINUTE, order_time, delivered_time) AS delivery_minutes
FROM order_detail
WHERE TIMESTAMPDIFF(MINUTE, order_time, delivered_time) < 30;



-- ===============================================================
-- 4️ .Total revenue generated by each food item

SELECT 
    f.food_id,
    f.food_name,
    ROUND(SUM(f.price_per_unit * ofd.quantity), 2) AS total_revenue
FROM order_food ofd
JOIN foods f ON ofd.food_id = f.food_id
GROUP BY f.food_id, f.food_name
ORDER BY total_revenue DESC;



-- ===============================================================
-- 5️. Second highest revenue-generating restaurant

SELECT 
    r.restaurant_id,
    r.restaurant_name,
    ROUND(SUM(f.price_per_unit * ofd.quantity), 2) AS total_revenue
FROM order_food ofd
JOIN foods f ON ofd.food_id = f.food_id
JOIN restaurant r ON ofd.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name
ORDER BY total_revenue DESC
LIMIT 1 OFFSET 1;



-- ===============================================================
-- 6️. 5 most popular food items (by total quantity sold)

SELECT 
    f.food_id,
    f.food_name,
    SUM(ofd.quantity) AS total_quantity_sold
FROM order_food ofd
JOIN foods f ON ofd.food_id = f.food_id
GROUP BY f.food_id, f.food_name
ORDER BY total_quantity_sold DESC
LIMIT 5;



-- ===============================================================
-- 7️.Top 3 Zomato employees with the highest average delivery rating
SELECT 
    employee_id,
    employee_name,
    employee_avg_rating
FROM zomato_employee
ORDER BY employee_avg_rating DESC
LIMIT 3;



-- ===============================================================
-- 8️ .Month with the highest number of orders placed
SELECT 
    DATE_FORMAT(order_time, '%Y-%m') AS order_month,
    COUNT(order_id) AS total_orders
FROM order_detail
GROUP BY order_month
ORDER BY total_orders DESC
LIMIT 1;



-- ===============================================================
-- 9 .Average order amount for each customer

SELECT 
    c.customer_id,
    c.customer_name,
    ROUND(AVG(order_total.total_amount), 2) AS avg_order_amount
FROM (
    SELECT 
        o.order_id,
        o.customer_id,
        SUM(f.price_per_unit * ofd.quantity) AS total_amount
    FROM order_detail o
    JOIN order_food ofd ON o.order_id = ofd.order_id
    JOIN foods f ON ofd.food_id = f.food_id
    GROUP BY o.order_id, o.customer_id
) AS order_total
JOIN customer c ON order_total.customer_id = c.customer_id
GROUP BY c.customer_id, c.customer_name
ORDER BY avg_order_amount DESC;



-- ===============================================================
-- 10 . Most frequent customer for each restaurant

SELECT 
    r.restaurant_id,
    r.restaurant_name,
    c.customer_id,
    c.customer_name,
    COUNT(o.order_id) AS total_orders
FROM order_detail o
JOIN restaurant r ON o.restaurant_id = r.restaurant_id
JOIN customer c ON o.customer_id = c.customer_id
GROUP BY r.restaurant_id, r.restaurant_name, c.customer_id, c.customer_name
HAVING COUNT(o.order_id) = (
    SELECT MAX(order_count)
    FROM (
        SELECT COUNT(*) AS order_count
        FROM order_detail
        WHERE restaurant_id = r.restaurant_id
        GROUP BY customer_id
    ) AS subquery
);



-- ===============================================================
-- 11️ .Total number of orders placed on weekends

SELECT 
    COUNT(order_id) AS weekend_orders
FROM order_detail
WHERE DAYOFWEEK(order_time) IN (1,7);  -- 1=Sunday, 7=Saturday



-- ===============================================================
-- 12️. Average delivery time (in minutes) — weekdays vs weekends

SELECT 
    CASE 
        WHEN DAYOFWEEK(order_time) IN (1,7) THEN 'Weekend'
        ELSE 'Weekday'
    END AS day_type,
    ROUND(AVG(TIMESTAMPDIFF(MINUTE, order_time, delivered_time)), 2) AS avg_delivery_minutes
FROM order_detail
GROUP BY day_type;



-- ===============================================================
-- 13️. Top 5 most expensive food items

SELECT 
    food_id,
    food_name,
    price_per_unit
FROM foods
ORDER BY price_per_unit DESC
LIMIT 5;



-- ===============================================================
-- 14️. Restaurant with the most diverse menu (most unique food items)

SELECT 
    r.restaurant_id,
    r.restaurant_name,
    COUNT(DISTINCT ofd.food_id) AS total_unique_foods
FROM order_food ofd
JOIN restaurant r ON ofd.restaurant_id = r.restaurant_id
GROUP BY r.restaurant_id, r.restaurant_name
ORDER BY total_unique_foods DESC
LIMIT 1;



-- ===============================================================
-- 15️ .Total payment amount for each payment type

SELECT 
    p.payment_type,
    ROUND(SUM(f.price_per_unit * ofd.quantity), 2) AS total_payment
FROM payment_table p
JOIN order_food ofd ON p.order_id = ofd.order_id
JOIN foods f ON ofd.food_id = f.food_id
GROUP BY p.payment_type
ORDER BY total_payment DESC;



-- ===============================================================


